// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZY__SkkyOrgz0mYgeo7je88ZnWSh45yE',
    appId: '1:625592839348:web:ef92cae66c7a1474f07be1',
    messagingSenderId: '625592839348',
    projectId: 'izuflutter',
    authDomain: 'izuflutter.firebaseapp.com',
    storageBucket: 'izuflutter.firebasestorage.app',
    measurementId: 'G-ZHMH3S8BZZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9A5tI0ql6Pyuu1xKxhB5Kf8XtEbL3us',
    appId: '1:625592839348:ios:9f1732d9b7d60bb9f07be1',
    messagingSenderId: '625592839348',
    projectId: 'izuflutter',
    storageBucket: 'izuflutter.firebasestorage.app',
    iosBundleId: 'com.example.konuAnlatim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9A5tI0ql6Pyuu1xKxhB5Kf8XtEbL3us',
    appId: '1:625592839348:ios:9f1732d9b7d60bb9f07be1',
    messagingSenderId: '625592839348',
    projectId: 'izuflutter',
    storageBucket: 'izuflutter.firebasestorage.app',
    iosBundleId: 'com.example.konuAnlatim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZY__SkkyOrgz0mYgeo7je88ZnWSh45yE',
    appId: '1:625592839348:web:301a9a3a1720cbc1f07be1',
    messagingSenderId: '625592839348',
    projectId: 'izuflutter',
    authDomain: 'izuflutter.firebaseapp.com',
    storageBucket: 'izuflutter.firebasestorage.app',
    measurementId: 'G-YW8Z4E1HMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApjDVi3wCPuMs9qaS988O_FzUP-NbHAes',
    appId: '1:625592839348:android:c173c388f78e346df07be1',
    messagingSenderId: '625592839348',
    projectId: 'izuflutter',
    storageBucket: 'izuflutter.firebasestorage.app',
  );

}